-- MySQL Script generated by MySQL Workbench
-- Sat Feb 20 19:54:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administration` (
  `idAdministration` INT NULL DEFAULT NULL,
  `idAdmin` VARCHAR(20) NULL DEFAULT NULL,
  `idChannel` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdministration`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Channels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Channels` (
  `idChannel` INT NULL DEFAULT NULL,
  `Channel_Name` VARCHAR(20) NULL DEFAULT NULL,
  `Channel_genre` VARCHAR(20) NULL DEFAULT NULL,
  `Administration_idAdministration` INT NOT NULL,
  `URL` VARCHAR(40) NULL,
  PRIMARY KEY (`idChannel`, `Administration_idAdministration`),
  INDEX `fk_Channel_Administration1_idx` (`Administration_idAdministration` ASC) VISIBLE,
  CONSTRAINT `fk_Channel_Administration1`
    FOREIGN KEY (`Administration_idAdministration`)
    REFERENCES `Administration` (`idAdministration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Admin` (
  `idAdmin` INT NULL DEFAULT NULL,
  `Admin_Name` VARCHAR(20) NULL DEFAULT NULL,
  `Admin_Password` VARCHAR(20) NULL DEFAULT NULL,
  `Administration_idAdministration` INT NOT NULL,
  PRIMARY KEY (`idAdmin`, `Administration_idAdministration`),
  INDEX `fk_Admin_Administration1_idx` (`Administration_idAdministration` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Administration1`
    FOREIGN KEY (`Administration_idAdministration`)
    REFERENCES `Administration` (`idAdministration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Favoris` (
  `idFavoris` INT NULL DEFAULT NULL,
  `idChannel` INT NULL DEFAULT NULL,
  `idKnown_User` INT NULL DEFAULT NULL,
  `Channels_idChannel` INT NOT NULL,
  `Channels_Administration_idAdministration` INT NOT NULL,
  PRIMARY KEY (`idFavoris`, `Channels_idChannel`, `Channels_Administration_idAdministration`),
  INDEX `fk_Favoris_Channels1_idx` (`Channels_idChannel` ASC, `Channels_Administration_idAdministration` ASC) VISIBLE,
  CONSTRAINT `fk_Favoris_Channels1`
    FOREIGN KEY (`Channels_idChannel` , `Channels_Administration_idAdministration`)
    REFERENCES `Channels` (`idChannel` , `Administration_idAdministration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Known_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Known_User` (
  `idKnown_User` INT NULL DEFAULT NULL,
  `KU_Name` VARCHAR(20) NULL DEFAULT NULL,
  `KUser_Password` VARCHAR(20) NULL DEFAULT NULL,
  `Date_de_Naissance` DATE NULL DEFAULT NULL,
  `E-mail` VARCHAR(30) NULL DEFAULT NULL,
  `Favoris_idFavoris` INT NOT NULL,
  `KU_Prenoml` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idKnown_User`, `Favoris_idFavoris`),
  INDEX `fk_Known_User_Favoris1_idx` (`Favoris_idFavoris` ASC) VISIBLE,
  CONSTRAINT `fk_Known_User_Favoris1`
    FOREIGN KEY (`Favoris_idFavoris`)
    REFERENCES `Favoris` (`idFavoris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnKown_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UnKown_User` (
  `idUnKown_User` INT NULL DEFAULT NULL,
  `UK_Username` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idUnKown_User`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Channel_has_UnKown_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Channel_has_UnKown_User` (
  `Channel_idChannel` INT NOT NULL,
  `UnKown_User_idUnKown_User` INT NOT NULL,
  PRIMARY KEY (`Channel_idChannel`, `UnKown_User_idUnKown_User`),
  INDEX `fk_Channel_has_UnKown_User_UnKown_User1_idx` (`UnKown_User_idUnKown_User` ASC) VISIBLE,
  INDEX `fk_Channel_has_UnKown_User_Channel1_idx` (`Channel_idChannel` ASC) VISIBLE,
  CONSTRAINT `fk_Channel_has_UnKown_User_Channel1`
    FOREIGN KEY (`Channel_idChannel`)
    REFERENCES `Channels` (`idChannel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Channel_has_UnKown_User_UnKown_User1`
    FOREIGN KEY (`UnKown_User_idUnKown_User`)
    REFERENCES `UnKown_User` (`idUnKown_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Known_User_has_Channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Known_User_has_Channel` (
  `Known_User_idKnown_User` INT NOT NULL,
  `Known_User_Favoris_idFavoris` INT NOT NULL,
  `Channel_idChannel` INT NOT NULL,
  PRIMARY KEY (`Known_User_idKnown_User`, `Known_User_Favoris_idFavoris`, `Channel_idChannel`),
  INDEX `fk_Known_User_has_Channel_Channel1_idx` (`Channel_idChannel` ASC) VISIBLE,
  INDEX `fk_Known_User_has_Channel_Known_User1_idx` (`Known_User_idKnown_User` ASC, `Known_User_Favoris_idFavoris` ASC) VISIBLE,
  CONSTRAINT `fk_Known_User_has_Channel_Known_User1`
    FOREIGN KEY (`Known_User_idKnown_User` , `Known_User_Favoris_idFavoris`)
    REFERENCES `Known_User` (`idKnown_User` , `Favoris_idFavoris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Known_User_has_Channel_Channel1`
    FOREIGN KEY (`Channel_idChannel`)
    REFERENCES `Channels` (`idChannel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
